name: deploy-staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Staging Server
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to Server by using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd office-zone/office-booking-backend
            git fetch origin main
            git checkout main
            cd ..
            sudo docker compose stop staging
            sudo docker compose build staging
            sudo docker compose start staging
