name: deploy-dev

on:
  push:
    branches: [develop]

jobs:
  update-doc:
    name: Update Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: SCP documentation to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./docs
          target: ./office-zone
  build:
    name: Build Development Binary
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: |
          docker build -t suryawarior44/office-zone:dev .
          docker save -o dev.tar suryawarior44/office-zone:dev
      - name: SCP docker image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: dev.tar
          target: ./office-zone
  deploy:
    needs: [build]
    name: Deploy Development Server
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run docker image on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ./office-zone
            docker load -i dev.tar
            rm dev.tar
            sudo docker compose kill dev
            sudo docker compose up -d dev
            docker system prune -f