name: deploy-dev

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy Development Server
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to Server by using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd office-zone/office-booking-backend
            git fetch origin develop
            git checkout develop
            cd ..
            sudo docker compose kill dev
            sudo docker compose up --build -d dev
